server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
eureka:
    client:
      service-url:
        defaultZone: "http://localhost:8761/eureka/"  # Trỏ về Eureka Server
    instance:
      prefer-ip-address: true