server:
  port: 8888

spring:
  application:
    name: api-gateway
  app:
    api-prefix:/api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

routes:
  - id: user-service
    uri: http://localhost:8080
    predicates:
      - Path=${app.api-prefix}/identity/**
    filters:
       - StripPrefix=1
  - id: profile-service
    uri: http://localhost:8081
    predicates:
      - Path=${app.api-prefix}/profile/users/**
